polling = read.csv("PollingData.csv")
str(polling)
table(polling$Year)
library("mice")
is.na(polling$DiffCount)
is.na(polling$PropR)
simple = polling[c("Rasmussen","SurveyUSA")]
summary(simple)
set.seed(144)
imputed = complete(mice(simple))
polling$Rasmussen = imputed$Rasmussen
polling$SurveyUSA = imputed$SurveyUSA
summary(polling)
Train = subset(polling, Year==2004 | Year == 2008)
Test = subset(polling, Year==2012)
table(Train$Republican)
mod1 = glm(Republican ~ SurveyUSA + DiffCount , data= Train, family = "binomial")
summary(mod1)
pred = predict(mod1, type = "response")
table(Train$Republican, pred >=0.5)
names(Train)
cor(Train[c("Rasmussen","SurveyUSA","DiffCount","PropR","Republican")])
mod2 = glm(Republican ~ SurveyUSA + Rasmussen + DiffCount + PropR, data= Train, family = binomial)
summary(mod2)
pred1 = predict(mod2, type = "response" )
table(Train$Republican, pred1>=0.5)
TestPred = predict(mod2, newdata= Test, type = "response")
table(Test$Republican, TestPred >= 0.5)
###CART
boston = read.csv("boston.csv")
str(boston)
plot(boston$LON , boston$LAT)
points(boston$LON[boston$CHAS == 1], boston$LAT[boston$CHAS==1], col="red", pch = 19)
##TEXT analytics
tweets = read.csv("tweets.csv", stringsAsFactors = FALSE)
str(tweets)
tweets$Negative = as.factor(tweets$Avg <= -1)
library("tm")
install.packages("SnowballC")
library("SnowballC")
corpus = Corpus(VectorSource(tweets$Tweet))
corpus = tm_map(corpus, content_transformer(tolower))
corpus = tm_map(corpus, removePunctuation)
corpus = tm_map(corpus, removeWords, c("apple", stopwords("english")))
corpus[[1]]
corpus = tm_map(corpus, stemDocument)
corpus[[1]]
dtm = DocumentTermMatrix(corpus)
inspect(dtm[1000:1005, 505:515])
findFreqTerms(dtm, lowfreq = 20)
sparse = removeSparseTerms(dtm, 0.995)
sparse
tweetsSparse = as.data.frame(as.matrix(sparse))
tweetsSparse
colnames(tweetsSparse) = make.names(colnames(tweetsSparse))
tweetsSparse$Negative = tweets$Negative
library(caTools)
set.seed(123)
split = sample.split(tweetsSparse$Negative, SplitRatio = 0.7)
train = subset(tweetsSparse, split = TRUE)
test = subset(tweetsSparse,split= FALSE)
str(test)
library(rpart)
library(rpart.plot)
tweetCart = rpart(Negative ~ ., data = train, method = "class")
prp(tweetCart)
predcart = predict(tweetCart, newdata= test, type = "class")
table(test$Negative,predcart)

